# Generated by Django 4.2.1 on 2025-05-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sfa_action',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False, verbose_name='行動ID')),
                ('mitsu_id', models.CharField(max_length=10, verbose_name='見積ID')),
                ('cus_id', models.CharField(default='', max_length=10, verbose_name='顧客ID')),
                ('day', models.CharField(max_length=10, verbose_name='日付')),
                ('type', models.IntegerField(verbose_name='種類')),
                ('text', models.TextField(blank=True, verbose_name='内容')),
                ('tel_result', models.CharField(blank=True, max_length=5, verbose_name='TEL結果')),
                ('alert_check', models.IntegerField(default=0, verbose_name='アラート')),
            ],
        ),
        migrations.CreateModel(
            name='Sfa_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitsu_id', models.CharField(max_length=255, unique=True, verbose_name='見積ID')),
                ('mitsu_num', models.CharField(max_length=255, verbose_name='見積番号')),
                ('mitsu_ver', models.IntegerField(verbose_name='見積バージョン')),
                ('mitsu_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='見積URL')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='ステータス')),
                ('order_kubun', models.CharField(blank=True, max_length=255, null=True, verbose_name='注文区分')),
                ('use_kubun', models.CharField(blank=True, max_length=255, null=True, verbose_name='利用区分')),
                ('use_youto', models.CharField(blank=True, max_length=255, null=True, verbose_name='使用用途')),
                ('nouhin_kigen', models.CharField(blank=True, max_length=255, null=True, verbose_name='納品期限日')),
                ('nouhin_shitei', models.CharField(blank=True, max_length=255, null=True, verbose_name='納品指定日')),
                ('nouki', models.CharField(blank=True, max_length=255, null=True, verbose_name='納期')),
                ('make_day', models.CharField(blank=True, max_length=255, verbose_name='見積作成日')),
                ('mitsu_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='初回見積日')),
                ('update_day', models.CharField(blank=True, max_length=255, verbose_name='更新日')),
                ('juchu_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='受注日')),
                ('hassou_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='発送完了日')),
                ('cus_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客ID')),
                ('sei', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓')),
                ('mei', models.CharField(blank=True, max_length=255, null=True, verbose_name='名')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='電話番号')),
                ('tel_mob', models.CharField(blank=True, max_length=255, null=True, verbose_name='携帯番号')),
                ('mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='メール')),
                ('pref', models.CharField(blank=True, max_length=255, null=True, verbose_name='都道府県')),
                ('com', models.CharField(blank=True, max_length=255, null=True, verbose_name='会社名')),
                ('com_busho', models.CharField(blank=True, max_length=255, null=True, verbose_name='部課名')),
                ('keiro', models.CharField(blank=True, max_length=255, null=True, verbose_name='流入経路')),
                ('money', models.IntegerField(blank=True, null=True, verbose_name='金額')),
                ('pay', models.CharField(blank=True, max_length=255, null=True, verbose_name='支払方法')),
                ('kakudo', models.CharField(blank=True, max_length=255, verbose_name='確度')),
                ('kakudo_day', models.CharField(blank=True, default='', max_length=255, verbose_name='予想年月')),
                ('bikou', models.TextField(blank=True, verbose_name='備考')),
                ('busho_id', models.CharField(max_length=255, verbose_name='部署ID')),
                ('tantou_id', models.CharField(max_length=255, verbose_name='担当ID')),
                ('show', models.IntegerField(default=0, verbose_name='表示')),
                ('hidden_day', models.CharField(blank=True, default='', max_length=255, verbose_name='非表示日時')),
                ('mw', models.IntegerField(default=0, verbose_name='メールワイズ')),
                ('last_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='ステータス最終日')),
                ('tel_last_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='TEL最終日')),
                ('mail_last_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='メール最終日')),
                ('s_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='s_ステータス')),
                ('s_use_youto', models.CharField(blank=True, max_length=255, null=True, verbose_name='s_使用用途')),
                ('s_nouki', models.CharField(blank=True, max_length=255, null=True, verbose_name='s_納期')),
                ('s_make_day', models.CharField(blank=True, max_length=255, verbose_name='s_見積作成日')),
                ('s_juchu_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='s_受注日')),
                ('s_hassou_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='s_発送完了日')),
                ('s_cus_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='s_顧客氏名')),
                ('s_keiro_tempo', models.IntegerField(default=0, verbose_name='s_対面あり')),
                ('s_tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='s_TEL最終日_回数')),
                ('s_tel_result', models.IntegerField(default=0, verbose_name='s_TEL色')),
                ('s_mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='s_メール最終日_回数')),
                ('s_mail_result', models.IntegerField(default=0, verbose_name='s_メール色')),
                ('s_memo1', models.TextField(blank=True, null=True, verbose_name='s_コメント表示用')),
                ('s_memo2', models.TextField(blank=True, null=True, verbose_name='s_コメントポップアップ用')),
            ],
        ),
    ]
