# Generated by Django 4.2.1 on 2025-05-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busho', models.CharField(max_length=15, verbose_name='部署')),
                ('busho_id', models.CharField(max_length=5, verbose_name='部署ID')),
                ('tantou', models.CharField(max_length=10, verbose_name='担当')),
                ('tantou_id', models.CharField(max_length=5, verbose_name='担当ID')),
                ('last_api', models.CharField(blank=True, max_length=255, verbose_name='最終API接続')),
            ],
        ),
    ]
