# Generated by Django 4.2.1 on 2025-05-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='sfa_data',
            name='eye',
            field=models.IntegerField(default=0, verbose_name='オープン表示'),
        ),
        migrations.AlterField(
            model_name='sfa_data',
            name='show',
            field=models.IntegerField(default=0, verbose_name='案件表示'),
        ),
    ]
