# Generated by Django 4.2.1 on 2025-05-20 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0003_sfa_data_eye_alter_sfa_data_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfa_data',
            name='mw',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_cus_name',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_hassou_day',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_juchu_day',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_keiro_tempo',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_mail',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_mail_result',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_make_day',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_memo1',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_memo2',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_nouki',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_tel',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_tel_result',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='s_use_youto',
        ),
    ]
