# Generated by Django 4.2.1 on 2025-05-20 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0004_remove_sfa_data_mw_remove_sfa_data_s_cus_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfa_data',
            name='nouki',
        ),
    ]
