# Generated by Django 4.2.1 on 2025-05-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0005_remove_sfa_data_nouki'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sfa_action',
        ),
    ]
