# Generated by Django 4.2.1 on 2025-05-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0006_delete_sfa_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='login_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ログインID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='busho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='部署'),
        ),
        migrations.AlterField(
            model_name='member',
            name='busho_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='部署ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tantou',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='担当'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tantou_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='担当ID'),
        ),
    ]
