# Generated by Django 4.2.1 on 2025-05-23 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0007_member_login_id_alter_member_busho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='login_id',
        ),
    ]
