# Generated by Django 4.2.1 on 2025-05-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0008_remove_member_login_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sfa_data',
            name='mitsu_ver',
            field=models.CharField(max_length=255, verbose_name='見積バージョン'),
        ),
    ]
