# Generated by Django 4.2.1 on 2025-06-03 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfa', '0009_alter_sfa_data_mitsu_ver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sfa_data',
            name='bikou',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='com_busho',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='kakudo',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='kakudo_day',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='keiro',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='last_status',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='mail_last_day',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='mitsu_day',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='pay',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='pref',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='tel_last_day',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='tel_mob',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='use_kubun',
        ),
        migrations.RemoveField(
            model_name='sfa_data',
            name='use_youto',
        ),
    ]
