# Generated by Django 4.2.1 on 2025-05-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(max_length=10, unique=True, verbose_name='顧客ID')),
                ('cus_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客URL')),
                ('cus_touroku', models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客登録日')),
                ('com', models.CharField(blank=True, max_length=255, null=True, verbose_name='会社名')),
                ('com_busho', models.CharField(blank=True, max_length=255, null=True, verbose_name='部課名')),
                ('sei', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓')),
                ('mei', models.CharField(blank=True, max_length=255, null=True, verbose_name='名')),
                ('pref', models.CharField(blank=True, max_length=255, null=True, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='市区町村')),
                ('address_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='番地')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='建物名')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='電話番号')),
                ('tel_search', models.CharField(blank=True, max_length=255, null=True, verbose_name='電話番号_検索')),
                ('tel_mob', models.CharField(blank=True, max_length=255, null=True, verbose_name='携帯番号')),
                ('tel_mob_search', models.CharField(blank=True, max_length=255, null=True, verbose_name='携帯番号_検索')),
                ('mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='メール')),
                ('grip_busho_id', models.CharField(blank=True, max_length=10, verbose_name='グリップ部署ID')),
                ('grip_tantou_id', models.CharField(blank=True, max_length=10, verbose_name='グリップ担当者ID')),
                ('mw', models.IntegerField(default=0, verbose_name='メールワイズ')),
                ('mw_busho_id', models.CharField(blank=True, max_length=10, verbose_name='メールワイズ_部署ID')),
                ('mw_tantou_id', models.CharField(blank=True, max_length=10, verbose_name='メールワイズ_担当ID')),
                ('mw_tantou', models.CharField(blank=True, max_length=10, verbose_name='メールワイズ_担当名')),
                ('mitsu_all', models.IntegerField(default=0, verbose_name='見積総数')),
                ('juchu_all', models.IntegerField(default=0, verbose_name='受注総数')),
                ('juchu_money', models.BigIntegerField(default=0, verbose_name='受注総金額')),
                ('mitsu_last', models.CharField(blank=True, max_length=255, null=True, verbose_name='最終見積日')),
                ('mitsu_last_busho_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='最終見積_部署ID')),
                ('mitsu_last_busho', models.CharField(blank=True, max_length=255, null=True, verbose_name='最終見積_部署名')),
                ('mitsu_last_tantou_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='最終見積_担当ID')),
                ('mitsu_last_tantou', models.CharField(blank=True, max_length=255, null=True, verbose_name='最終見積_担当名')),
                ('juchu_last', models.CharField(blank=True, max_length=255, null=True, verbose_name='最終受注日')),
                ('contact_last', models.CharField(blank=True, max_length=255, null=True, verbose_name='最終コンタクト日')),
                ('taimen', models.BooleanField(verbose_name='対面')),
                ('royal', models.IntegerField(default=0, verbose_name='ロイヤル')),
            ],
        ),
    ]
