# Generated by Django 4.2.1 on 2025-06-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crm_action',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False, verbose_name='行動ID')),
                ('cus_id', models.CharField(max_length=10, verbose_name='顧客ID')),
                ('tantou_id', models.CharField(max_length=10, verbose_name='担当ID')),
                ('day', models.CharField(max_length=10, verbose_name='日付')),
                ('type', models.IntegerField(verbose_name='種類')),
                ('text', models.TextField(blank=True, verbose_name='内容')),
                ('alert_check', models.IntegerField(default=0, verbose_name='アラート')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(max_length=10, unique=True, verbose_name='顧客ID')),
                ('cus_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客URL')),
                ('cus_touroku', models.CharField(blank=True, max_length=255, null=True, verbose_name='顧客登録日')),
                ('com', models.CharField(blank=True, max_length=255, null=True, verbose_name='会社名')),
                ('com_busho', models.CharField(blank=True, max_length=255, null=True, verbose_name='部課名')),
                ('sei', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓')),
                ('mei', models.CharField(blank=True, max_length=255, null=True, verbose_name='名')),
                ('pref', models.CharField(blank=True, max_length=255, null=True, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='市区町村')),
                ('address_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='番地')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='建物名')),
                ('tel', models.CharField(blank=True, max_length=255, null=True, verbose_name='電話番号')),
                ('tel_search', models.CharField(blank=True, max_length=255, null=True, verbose_name='電話番号_検索')),
                ('tel_mob', models.CharField(blank=True, max_length=255, null=True, verbose_name='携帯番号')),
                ('tel_mob_search', models.CharField(blank=True, max_length=255, null=True, verbose_name='携帯番号_検索')),
                ('mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='メール')),
                ('juchu_all', models.IntegerField(default=0, verbose_name='受注総数')),
                ('juchu_money', models.BigIntegerField(default=0, verbose_name='受注総金額')),
                ('update_last_day', models.CharField(blank=True, max_length=255, null=True, verbose_name='最終更新日')),
                ('update_last_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='最終更新_見積番号')),
                ('update_last_ver', models.CharField(blank=True, max_length=255, null=True, verbose_name='最終更新_バージョン')),
                ('bikou', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
    ]
