# Generated by Django 4.2.1 on 2025-05-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='royal',
        ),
        migrations.AddField(
            model_name='customer',
            name='update_last',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終更新日'),
        ),
    ]
