# Generated by Django 4.2.1 on 2025-06-11 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='bikou',
        ),
    ]
