# Generated by Django 4.2.1 on 2025-05-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_customer_royal_customer_update_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='update_last_day',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終更新日'),
        ),
        migrations.AddField(
            model_name='customer',
            name='update_last_num',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終更新_見積番号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='update_last_ver',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終更新_バージョン'),
        ),
    ]
