# Generated by Django 4.2.1 on 2025-05-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customer_update_last_day_customer_update_last_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='grip_busho_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='grip_tantou_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mw',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mw_busho_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mw_tantou',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mw_tantou_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='bikou',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
    ]
