# Generated by Django 4.2.1 on 2025-05-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_customer_grip_busho_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crm_action',
            fields=[
                ('act_id', models.AutoField(primary_key=True, serialize=False, verbose_name='行動ID')),
                ('cus_id', models.CharField(max_length=10, verbose_name='顧客ID')),
                ('day', models.CharField(max_length=10, verbose_name='日付')),
                ('type', models.IntegerField(verbose_name='種類')),
                ('text', models.TextField(blank=True, verbose_name='内容')),
                ('alert_check', models.IntegerField(default=0, verbose_name='アラート')),
            ],
        ),
    ]
