# Generated by Django 4.2.1 on 2025-05-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_crm_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_last',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='juchu_last',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mitsu_last_busho',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mitsu_last_busho_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mitsu_last_tantou',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mitsu_last_tantou_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='update_last',
        ),
    ]
