# Generated by Django 4.2.1 on 2025-05-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_remove_customer_contact_last_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mitsu_last_busho',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終見積_部署名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mitsu_last_busho_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='最終見積_部署ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mitsu_last_tantou',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終見積_担当名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mitsu_last_tantou_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='最終見積_担当ID'),
        ),
    ]
