# Generated by Django 4.2.1 on 2025-05-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_customer_mitsu_last_busho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='juchu_last',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='最終受注日'),
        ),
    ]
