# Generated by Django 4.2.1 on 2025-05-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_customer_juchu_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_action',
            name='tantou_id',
            field=models.CharField(default=0, max_length=10, verbose_name='担当ID'),
            preserve_default=False,
        ),
    ]
