# Generated by Django 4.2.1 on 2025-06-03 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_crm_action_tantou_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='juchu_last',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mitsu_all',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mitsu_last',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mitsu_last_busho',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mitsu_last_busho_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mitsu_last_tantou',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='mitsu_last_tantou_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='taimen',
        ),
    ]
